### ISSUE TITLE
Simple 'vertical-align' syntax

### ISSUE THREAD

**Issue by Hawry** [Hawry/hawgrid#9]
Implement a way to set vertical-align without the use of tables or other weird hacks.

**Comment by Hawry** [comment]
Put 
```css
.v-container {
    display:flex;
    align-items: center;
}
```
on the parent container (works for `small` columns at least)

**Comment by Hawry** [comment]
More fiddles:
```css

.v-container {
    display:flex;
    align-items: center;
}


.db {
        background-color: aqua;
}
.v-container {
    display:flex;
    align-items: center;
}

.v-container .text-right {
    justify-content: flex-end;
}
```
This collides with `small-up` etc. since the display-property is changed. Make sure to check that out
